from main import *

class TRFunctions():

    def updLanguage(self):
        if self.ui.comLanguage.currentText() == 'Espanol':
            TRFunctions.inSpanish(self)
        elif self.ui.comLanguage.currentText() == 'Italiano':
            self.ui.retranslateUi(self)


    def inSpanish(self):
        ui = self.ui
        ui.tblHall.setHorizontalHeaderLabels(['Paridera', 'Madres', 'Situacion','Curva','Dia Curva','KG/Dia','Kg/Racion','Repartido'])
        ui.tblCurve.setHorizontalHeaderLabels(['Tipo','Dia','Cantitad'])
        ui.tblTime.setHorizontalHeaderLabels(['Dalle','Alle','Activo'])
        ui.tblSow.setHorizontalHeaderLabels(['Nombre Madre','Gestido'])
        ui.tblBox.setHorizontalHeaderLabels(['Paridera','Pos. Sala','Pos. Paridera','Pos. COM','Sit. COM'])
        ui.btnHallRem.setText('ELIMINAR GESTION')
        ui.btnHallAdd.setText('INSERTAR MADRE')
        ui.btnHallExp.setText('EXPORTAR CONSUMO')
        ui.btnHallLoadCur.setText('SUBIR CURVA AUTO')
        ui.btnCurveExp.setText('EXPORTAR CURVA')
        ui.btnCurveSave.setText('EDITAR CURVA')
        ui.btnCurveRem.setText('ELIMINAR CURVA')
        ui.btnCurveMen.setText('MENU PRINCIPAL')
        ui.btnTimeUpd.setText('ACTUALIZAR DATOS')
        ui.btnTimeSave.setText('GUARDAR TIEMPOS')
        ui.btnTimeRem.setText('RESET TIEMPOS')
        ui.btnTimeMen.setText('MENU PRINCIPAL')
        ui.lblTimeDur.setText('Duraciòn Comida Actual')
        ui.lblTimeAct.setText('Comida Activa')
        ui.lblTimeNrAct.setText('Numero de la Comida Activa')
        ui.lblTimeRat.setText('Racionamento')
        ui.lblSow.setText('Datos Madres')
        ui.lblBox.setText('Datos Sal Paridera')
        ui.btnDataRemSow.setText('Eliminar Madre')
        ui.btnDataRemBox.setText('Eliminar Sal Paridera')
        ui.btnDataSaveCom.setText('Asociar Pos. COM')
        ui.lblDataTotSow.setText('Madres Totales')
        ui.lblDataFreeSow.setText('No Asignado')
        ui.lblDataTotBox.setText('Box Total')
        ui.lblDataFreeBox.setText('No Asignado')
        ui.btnDataUpd.setText('ACTUALIZAR DATOS')
        ui.btnDataRem.setText('REINICIO DATOS')
        ui.btnDataAdd.setText('AGREGAR DATOS')
        ui.btnDataMen.setText('MENU PRINCIPAL')
        ui.lblAddSelBox.setText('Seleccionar Paridera')
        ui.lblAddSelSow.setText('Seleccionar Madre')
        ui.lblAddSelCur.setText('Seleccionar Curva')
        ui.lblAddSelEntryDate.setText('Fecha de Entrada')
        ui.lblAddSelCurDate.setText('Dia in Curva')
        ui.lblAddBirth.setText('Parto Occurio')
        ui.lblAddNotes.setText('Notas Adicionales')
        ui.lblAddSelPigBirth.setText('Lechones Nacidos')
        ui.lblAddSelPigRealBirth.setText('Lechones Nacidos Vivo')
        ui.lblAddSelPigWeight.setText('Peso Total')
        ui.lblAddSelPigDate.setText('Fecha de Parto')
        ui.btnAddUpd.setText('ACTUALIZAR DATOS')
        ui.btnAddRes.setText('REINICIAR DATOS')
        ui.btnAddMen.setText('MENU PRINCIPAL')
        ui.btnAddAdd.setText('INTRODUCIR DATOS IN SAL')
        ui.btnDataBoxAdd.setText('Introducir Sal Paridera')
        ui.lblDataBoxAdd.setText('Introducir Sal Paridera')
        ui.lblDataNrBoxAdd.setText('Numero de Box para Insertar')
        ui.lblDataNrHallAdd.setText('Numero de Sal en el cual Insertar')
        ui.btnDataSowAdd.setText('Introducir Madres')
        ui.lblDataSow.setText('Introducir Madres')
        ui.lblDataSowName.setText('Numero de Madres para Insertar')
        ui.btnHall.setText('Sal')
        ui.btnCurve.setText('Curva')
        ui.btnTime.setText('Tiempo')
        ui.btnCom.setText('Comunication')
        ui.btnData.setText('Datos')
        ui.btnMenu.setText('Menu Principal')
        ui.btnStock.setText('Almacenamiento')
